service: encuesta-metalsa
app: survey
tenant: birkoffh

provider:
  name: aws
  runtime: python3.7
  timeout: 30
#  stage: dev
  region: us-east-1
#  role: lambdaAssumeRole

  profile: ${file(settings.${opt:stage}.json):profile}

  environment:
    ENVIRONMENT: ${opt:stage}
    DB_CONNECTION: ${file(settings.${opt:stage}.json):database_connection}

package:
  include:
    - ../../handler.py
#    - ../../requirements.txt
    - ../../modules/**
#    - ../../../config/*
  exclude:
    - settings.*.json

functions:
  initdb:
    handler: handler.create_table

  create:
    handler: handler.create
    events:
      - http:
          path: /encuesta
          method: post
          cors: true
  resultados:
    handler: handler.statistics
    events:
      - http:
          path: /resultados
          method: get
          cors: true

resources:
  Resources:
    MyDB:
      DeletionPolicy: Delete
      Properties:
        AllocatedStorage: "5"
        DBInstanceClass: "db.t2.micro"
        DBName: "encuestas"
        Engine: MySQL
        MasterUserPassword: "encuestas"
        MasterUsername: "comedor"
        Tags:
          - Key: Name
            Value: "EncuestaComedor"
      Type: "AWS::RDS::DBInstance"

plugins:
  - serverless-python-requirements
